AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  AlbSecurityGroup:
    Type: String

Resources:

  AlbLogBucket:
    Type: AWS::S3::Bucket
    
    Properties:
      BucketName: !Sub "${EnvironmentName}-${AWS::AccountId}-alb-logs"
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false

  AlbLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AlbLogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ALBLogDeliveryWrite
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::127311923021:root
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${AlbLogBucket}/AWSLogs/${AWS::AccountId}/*"
         
          - Sid: ALBLogDeliveryAclCheck
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::127311923021:root
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${AlbLogBucket}"

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvironmentName}-alb"
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref AlbSecurityGroup
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: "true"
        - Key: access_logs.s3.bucket
          Value: !Ref AlbLogBucket

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvironmentName}-frontend-tg"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port

  ApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${EnvironmentName}-api-tg"
      Port: 5000
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !GetAtt FrontendTargetGroup.Arn

  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 10
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt ApiTargetGroup.Arn



Outputs:
  ALBDNS:
    Value: !GetAtt ALB.DNSName

  ALBZoneId:
    Value: !GetAtt ALB.CanonicalHostedZoneID

  ALBName:
    Value: !Ref ALB

  Listener:
    Value: !Ref Listener

  FrontendTargetGroupArn:
    Value: !GetAtt FrontendTargetGroup.Arn

  ApiTargetGroupArn:
    Value: !GetAtt ApiTargetGroup.Arn