AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-microservice-cluster"

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  ClusterName:
    Value: !Ref ECSCluster

  ClusterArn:
    Value: !GetAtt ECSCluster.Arn