AWSTemplateFormatVersion: "2010-09-09"
Description: Task Definitions for Frontend, API, and Worker

Parameters:

  EnvironmentName:
    Type: String

  ExecutionRoleArn:
    Type: String

  TaskRoleArn:
    Type: String

  QueueUrl:
    Type: String


Resources:
  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-frontend-task"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-frontend"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/frontend:latest"
          PortMappings:
            - ContainerPort: 80
            
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  ApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-api-taskdef"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-api"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/api:latest"
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: AWS_REGION
              Value: !Sub "${AWS::Region}"
            - Name: QUEUE_URL
              Value: !Ref QueueUrl

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-worker-taskdef"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-worker"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/worker:latest"
          Environment:
            - Name: AWS_REGION
              Value: !Sub "${AWS::Region}"
            - Name: QUEUE_URL
              Value: !Ref QueueUrl

      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  FrontendTaskDefinitionArn:
    Value: !GetAtt FrontendTaskDefinition.Arn

  ApiTaskDefinitionArn:
    Value: !GetAtt ApiTaskDefinition.Arn

  WorkerTaskDefinitionArn:
    Value: !GetAtt WorkerTaskDefinition.Arn