AWSTemplateFormatVersion: "2010-09-09"
Description: Task Definitions for Frontend, API, and Worker

Parameters:

  EnvironmentName:
    Type: String

  ExecutionRoleArn:
    Type: String

  TaskRoleArn:
    Type: String

  QueueUrl:
    Type: String

  FrontendRepositoryUri:
    Type: String

  FrontendImageTag:
    Type: String

  ApiRepositoryUri:
    Type: String

  ApiImageTag:
    Type: String

  WorkerRepositoryUri:
    Type: String

  WorkerImageTag:
    Type: String 


Resources:

  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${EnvironmentName}-frontend"
      RetentionInDays: 14

  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${EnvironmentName}-api"
      RetentionInDays: 14

  WorkerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${EnvironmentName}-worker"
      RetentionInDays: 14

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-frontend-task"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-frontend"
          Image: !Sub "${FrontendRepositoryUri}:${FrontendImageTag}"
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendLogGroup
              awslogs-region: !Sub "${AWS::Region}"
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  ApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-api-taskdef"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-api"
          Image: !Sub "${ApiRepositoryUri}:${ApiImageTag}"
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: AWS_REGION
              Value: !Sub "${AWS::Region}"
            - Name: QUEUE_URL
              Value: !Ref QueueUrl
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ApiLogGroup
              awslogs-region: !Sub "${AWS::Region}"
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${EnvironmentName}-worker-taskdef"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRoleArn
      TaskRoleArn: !Ref TaskRoleArn
      ContainerDefinitions:
        - Name: !Sub "${EnvironmentName}-worker"
          Image: !Sub "${WorkerRepositoryUri}:${WorkerImageTag}"
          Environment:
            - Name: AWS_REGION
              Value: !Sub "${AWS::Region}"
            - Name: QUEUE_URL
              Value: !Ref QueueUrl
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref WorkerLogGroup
              awslogs-region: !Sub "${AWS::Region}"
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  FrontendTaskDefinitionArn:
    Value: !Ref FrontendTaskDefinition

  ApiTaskDefinitionArn:
    Value: !Ref ApiTaskDefinition

  WorkerTaskDefinitionArn:
    Value: !Ref WorkerTaskDefinition





