version: 0.2

phases:

  build:
    commands:
      - echo Checking if front-update.html exists
      - test -f app/frontend-update/front-update.html

      - echo Checking file is not empty
      - test -s app/frontend-update/front-update.html

      - echo Checking for required text
      - grep "Frontend Version" app/frontend-update/front-update.html

      - echo Frontend tests passed
