version: 0.2

env:
  variables:
    ENVIRONMENT: prod

phases:
  pre_build:
    commands:
    
      - REGION=$AWS_DEFAULT_REGION

      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

      - REPOSITORY_NAME=${ENVIRONMENT}-frontend-repository
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -f app/frontend-update/front-updateDockerfile.dockerfile -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Writing image definitions..."

      - CONTAINER_NAME=${ENVIRONMENT}-frontend

      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
